[package]
name = "monte"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.4.0"
serde = { version = "1.0.228", features = ["derive"] }
chrono = "0.4"
chrono-tz = "0.10.4"
rand = "0.8"
rand_distr = "0.4"
rayon = "1.10"